name: flutterapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+2
environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  image_picker: ^1.1.2
  http: ^0.13.6
  path: ^1.9.0
  path_provider: ^2.0.11
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/image1.png
